name: Deploy RS-STE to Modal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          # Install Modal and FastAPI with standard dependencies
          pip install modal fastapi[standard]
          
          # Install all dependencies needed for imports in modal_app.py
          pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
          pip install numpy==1.19.2 Pillow==9.5.0 omegaconf
          pip install torchmetrics==0.5 albumentations==0.4.3 pytorch-lightning==1.4.2
          pip install opencv-python tensorboard editdistance einops tqdm
          pip install pydantic>=2.0.0 typing-extensions

      - name: Configure Modal
        run: |
          # Create the .modal directory
          mkdir -p ~/.modal
          
          # Create the token file with proper permissions
          touch ~/.modal.toml
          chmod 600 ~/.modal.toml
          
          # Write the exact token configuration format
          cat > ~/.modal.toml << EOF
          [${{ secrets.MODAL_USERNAME }}]
          token_id = "${{ secrets.MODAL_TOKEN_ID }}"
          token_secret = "${{ secrets.MODAL_TOKEN_SECRET }}"
          active = true
          EOF

      - name: Deploy to Modal
        run: |
          # Deploy directly
          modal deploy modal_app.py

      - name: Verify deployment
        run: |
          echo "Deployment completed. The service is now available at:"
          echo "https://${{ secrets.MODAL_USERNAME }}--rs-ste-api.modal.run"
