name: Deploy RS-STE to Modal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install modal fastapi[standard]  # Install Modal and FastAPI with standard dependencies

      - name: Configure Modal
        run: |
          # Create the .modal directory
          mkdir -p ~/.modal
          
          # Create the token file with proper permissions
          touch ~/.modal.toml
          chmod 600 ~/.modal.toml
          
          # Write the exact token configuration format
          cat > ~/.modal.toml << EOF
          [${{ secrets.MODAL_USERNAME }}]
          token_id = "${{ secrets.MODAL_TOKEN_ID }}"
          token_secret = "${{ secrets.MODAL_TOKEN_SECRET }}"
          active = true
          EOF

      - name: Deploy to Modal
        run: |
          # Deploy directly
          modal deploy modal_app.py

      - name: Verify deployment
        run: |
          echo "Deployment completed. The service is now available at:"
          echo "https://${{ secrets.MODAL_USERNAME }}--rs-ste-api.modal.run"
